Updated feedback in postprocessing image
LucidtechAI/cradl-docs pull request #197
Opened 2024-03-19 15:32 UTC by staalezh

2024-03-21 08:50 UTC, augustak requested changes

2024-03-21 08:50 UTC, augustak commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +    ground_truth = []
Ground truth for line items need to have a nested structure similar to predictions V1 format

2024-04-03 13:12 UTC, magnurud requested changes

2024-04-03 13:12 UTC, magnurud commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +        is_line_item = isinstance(feedback[label], list)
Use .items()  
```suggestion
    for label field_feedback in feedback.items():
        is_line_item = isinstance(field_feedback, list)
```

2024-04-03 13:12 UTC, magnurud commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +                for line_label in line:
use .items()

2024-04-03 13:12 UTC, magnurud commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +                    if should_post_feedback(line, line_label):
line_label will never be a key in feedback

2024-04-03 13:12 UTC, magnurud commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +        return not item[label].get('automated') or feedback[label].get('isEdited')
```suggestion
    def should_post_feedback(item):
        return not item.get('automated', True) or item.get('isEdited', False)
```

2024-04-04 07:13 UTC, augustak requested changes

2024-04-04 07:13 UTC, augustak commented on docs/workflows/transitions/postprocess/postprocess/feedback_and_export.py
> +        except requests.exceptions.RequestException as re:
```suggestion
        except (requests.exceptions.RequestException, KeyError) as re:
```

2024-04-19 11:56 UTC, magnurud approved these changes

2024-04-19 11:58 UTC, merged